name: analyze

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Prepare tooling
        run: |
          sudo apt-get update
          sudo apt-get -y install gcc cmake make valgrind liblog4cxx-dev libexiv2-dev python3-pip python3-setuptools python3-wheel
          pip3 install conan
          export PATH=$PATH:$HOME/.local/bin
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan
          mkdir build

      - name: Get dependencies
        working-directory: build
        run: |
          export PATH=$PATH:$HOME/.local/bin
          conan install --build=missing ../ -s compiler.libcxx=libstdc++11

      - name: Configure
        working-directory: build
        run: cmake -DCMAKE_BUILD_TYPE=Release ../source

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        with:
          languages: cpp

      - name: Build
        working-directory: build
        run: cmake --build . --config Release -- -j

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v1
